import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation/Navigation";
import Footer from "./components/footer/Footer";

const inter = League_Spartan({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
  weight: "variable"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
